Repository gbowne1/json-maestro, pull requests merged in 2024-10, with the labels that each got.

#8 Makes Package installable by pip
  setup.py
  src/jsonmaestro/__init__.py
  src/jsonmaestro/jsonmaestro.py
  src/jsonmaestro/main.py
Labels: enhancement

#10 Fix setup.py
  .gitignore
  data/.vscode/extensions.json
  data/.vscode/keybindings.json
  data/.vscode/launch.json
  data/.vscode/pylance.json
  data/.vscode/settings.json
  data/.vscode/tasks.json
  setup.py
Labels: bug

#12 Workflow for checking if package is installable by pip
  .editorconfig
  .github/workflows/pip-install.yml
Labels: enhancement

#15 Fix unable to find config files
  requirements.txt
  src/jsonmaestro/__init__.py
  src/jsonmaestro/helpers.py
  src/jsonmaestro/jsonmaestro.py
  src/jsonmaestro/main.py
  tests/test_format_helpers.py
  tests/test_json_cleaner.py
Labels: bug, enhancement

#16 add repository url in setup.py
  setup.py
Labels: enhancement

#17 Update README.md
  README.md
Labels: documentation

#19 Fix not writing in non-interactive mode
  src/jsonmaestro/main.py
Labels: bug, enhancement

#25 fixing spelling in main.py
  src/jsonmaestro/main.py
Labels: enhancement

#27 Cleanup tests
  .github/workflows/test.yml
  tests/test_format_helpers.py
  tests/test_json_cleaner.py
Labels: bug

#34 Packaging
  .github/workflows/pip-install.yml
  README.md
  dev.requirements
  pyproject.toml
  requirements.txt
  setup.py
Labels: bug
